//! Íconos vectoriales (Phosphor, variante regular) como glifos de fuente.
pub use egui_phosphor::regular::{
    ARROWS_OUT_SIMPLE, CARET_DOWN, CARET_LEFT, CARET_RIGHT, CARET_UP, CHART_BAR, DISC, FOLDER_OPEN, GEAR, HEART, LIST_BULLETS, MAGNIFYING_GLASS,
    MICROPHONE_STAGE, MUSIC_NOTES, PAUSE, PLAY, QUEUE, REPEAT, REPEAT_ONCE, SHUFFLE, SKIP_BACK, SKIP_FORWARD,
    SPEAKER_HIGH, SPEAKER_LOW, SPEAKER_X, TEXT_ALIGN_LEFT, USER, WAVEFORM, X,
};
