//! Íconos vectoriales (Phosphor, variante regular) como glifos de fuente.
pub use egui_phosphor::regular::{
    ARROW_CLOCKWISE, ARROWS_OUT_SIMPLE, CARET_DOWN, CARET_LEFT, CARET_RIGHT, CARET_UP, CHART_BAR, DISC, DOWNLOAD_SIMPLE, FOLDER_OPEN, GEAR, HEART, LIST_BULLETS, MAGNIFYING_GLASS,
    MICROPHONE_STAGE, MUSIC_NOTES, PAUSE, PLAY, PLUS, QUEUE, REPEAT, REPEAT_ONCE, SHUFFLE, SKIP_BACK, SKIP_FORWARD,
    SPEAKER_HIGH, SPEAKER_LOW, SPEAKER_X, TEXT_ALIGN_LEFT, TRASH, UPLOAD_SIMPLE, USER, WARNING, WAVEFORM, X,
};
